name: smoke
channels:
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - polars
  - pathlib
  - scipy
  - scikit-learn
  - statsmodels
  - pyarrow
prefix: C:\Users\danil\anaconda3\envs\smoke
